version: "3"
services:
  alpine-varnish:
    build:
      context: .
    image: augustash/alpine-varnish:3.0.0
    labels:
      - "com.augustash.description=August Ash Alpine Varnish Image"
      - "com.augustash.development-only"
    depends_on:
      - web
    ports:
      - "8080:80"
    environment:
      - VARNISH_CACHE_SIZE=32M
  web:
    image: augustash/alpine-nginx
    environment:
      - NGINX_DH_SIZE=128
